/*
 * Copyright 2025 The Kubernetes Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { composeStories, type Meta, setProjectAnnotations, type StoryFn } from '@storybook/react';
import { act, render as testingLibraryRender, waitFor } from '@testing-library/react';
import { getWorker } from 'msw-storybook-addon';
import path from 'path';
import * as previewAnnotations from '../.storybook/preview';

vi.mock('./lib/k8s/api/v1/clusterRequests', async () => {
  const actual = await vi.importActual('./lib/k8s/api/v1/clusterRequests');
  return {
    ...(actual as any),
    clusterRequest: vi.fn((url, ...args) => {
      if (url === '/version') {
        return Promise.resolve({ gitVersion: 'v1.2.3' });
      }
      return (actual as any).clusterRequest(url, ...args);
    }),
  };
});

const annotations = setProjectAnnotations([previewAnnotations, { testingLibraryRender }]);
beforeAll(annotations.beforeAll!);

type StoryFile = {
  default: Meta;
  [name: string]: StoryFn | Meta;
};

const compose = (entry: StoryFile) => {
  try {
    const stories = composeStories(entry);
    return stories;
  } catch (e) {
    throw new Error(
      `There was an issue composing stories for the module: ${JSON.stringify(entry)}, ${e}`
    );
  }
};

function getAllStoryFiles() {
  // Place the glob you want to match your story files
  const storyFiles = Object.entries(
    import.meta.glob<StoryFile>('./**/*.stories.tsx', {
      eager: true,
    })
  );

  return storyFiles.map(([filePath, storyFile]) => {
    const storyDir = path.dirname(filePath);
    const componentName = path.basename(filePath).replace(/\.(stories|story)\.[^/.]+$/, '');
    return { filePath, storyFile, componentName, storyDir };
  });
}

// Recreate similar options to Storyshots. Place your configuration below
const options = {
  storyKindRegex: /^.*?DontTest$/,
  snapshotsDirName: '__snapshots__',
  snapshotExtension: '.stories.storyshot',
};

vi.mock('@iconify/react', () => ({
  Icon: () => null,
  InlineIcon: () => null,
  addCollection: () => {},
}));

vi.mock('@monaco-editor/react', () => ({
  Editor: () => <div className="mock-monaco-editor" />,
  DiffEditor: () => <div className="mock-monaco-diff-editor" />,
  useMonaco: () => null,
  loader: { config: () => null },
  default: () => <div className="mock-monaco-editor" />,
}));

window.matchMedia = () => ({
  matches: false,
  addListener: () => {},
  removeListener: () => {},
  media: '',
  onchange: () => {},
  addEventListener: () => {},
  removeEventListener: () => {},
  dispatchEvent: () => true,
});
/**
 * Recursively walks the tree and replaces any usage of useId
 */
function replaceUseId(node: any) {
  const attributesToReplace = [
    'id',
    'for',
    'aria-describedby',
    'aria-labelledby',
    'aria-controls',
    'aria-activedescendant',
    'aria-owns',
  ];
  if (node.nodeType === Node.ELEMENT_NODE) {
    // Normalize attributes' values: collapse whitespace and normalize dynamic ids
    for (const attr of Array.from(node.attributes || []) as any) {
      if (!attr || !attr.name) continue;

      // Collapse whitespace/newlines in attribute values to avoid snapshot diffs
      const collapsed = attr.value.replace(/\s+/g, ' ').trim();

      if (attributesToReplace.includes(attr.name)) {
        // React useId values often include ":" or other runtime fragments — normalize them
        if (/:/.test(collapsed) || /^(mui|headlamp)-?id-?\d*/i.test(collapsed)) {
          node.setAttribute(attr.name, ':mock-test-id:');
          continue;
        }

        // Recharts autogenerated ids
        if (attr.name === 'id' && /(recharts|recharts-)/i.test(collapsed)) {
          node.setAttribute(attr.name, 'recharts-id');
          continue;
        }
      }

      // Fallback: set collapsed value back (removes newlines/extra whitespace)
      if (collapsed !== attr.value) {
        node.setAttribute(attr.name, collapsed);
      }
    }

    // Normalize className string: collapse whitespace, replace dynamic tokens, sort classes
    if (node.className && typeof node.className === 'string') {
      let classes = node.className.replace(/\s+/g, ' ').trim().split(' ');

      classes = classes
        .map(c => {
          if (!c) return c;
          // Normalize xterm owner class
          c = c.replace(/xterm-dom-renderer-owner-\d+/g, 'xterm-dom-renderer-owner');
          // Normalize Emotion css hashes
          if (/^css-/.test(c)) return 'css-hash';
          // Normalize MUI generated classes like MuiOutlinedInput-root-abcdef  -> MuiOutlinedInput
          c = c.replace(/(Mui[A-Za-z0-9]+)(?:-[A-Za-z0-9-_]+)+/g, '$1');
          // Strip trailing numeric hashes like "-12345"
          c = c.replace(/-[0-9]+$/g, '');
          return c;
        })
        .filter(Boolean)
        .sort();

      node.className = classes.join(' ');
    }
  }

  // Recursively update child nodes
  for (const child of node.childNodes || []) {
    replaceUseId(child);
  }
}

describe('Storybook Tests', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });
  afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
  });

  getAllStoryFiles().forEach(({ storyFile, componentName, storyDir }) => {
    const meta = storyFile.default;
    const title = meta.title || componentName;

    if (options.storyKindRegex.test(title) || meta.parameters?.storyshots?.disable) {
      // Skip component tests if they are disabled
      return;
    }

    describe(title, () => {
      const stories = Object.entries(compose(storyFile)).map(([name, story]) => ({
        name,
        story,
      }));

      if (stories.length <= 0) {
        throw new Error(
          `No stories found for this module: ${title}. Make sure there is at least one valid story for this module, without a disable parameter, or add parameters.storyshots.disable in the default export of this file.`
        );
      }

      stories.forEach(({ name, story }) => {
        if (story.parameters?.storyshots?.disable) return;

        test(
          name,
          async () => {
            // Keep track of sent requests to wait for the to finish
            let requestsSent = 0;
            let requestsEnded = 0;
            const worker = getWorker();
            function onStart() {
              requestsSent++;
            }
            function onEnd() {
              requestsEnded++;
            }
            worker.events.on('request:start', onStart);
            worker.events.on('request:end', onEnd);

            const unhandledRequests: Array<string> = [];

            function onUnhandledRequest(e: { request: Request }) {
              unhandledRequests.push(e.request.url);
            }
            worker.events.on('request:unhandled', onUnhandledRequest);

            act(() => {
              previewAnnotations.queryClient.clear();
            });
            await act(async () => {
              await story.run();
            });

            // There are a bunch of waterfall requests in the stories
            // So to make sure all requests are sent we need to skip over some ticks
            const tickSkipCount = 10;
            for (let i = 0; i < tickSkipCount; i++) {
              // Advance timers enough for stuff to appear
              // but not too much that things like notifications/toasts are hidden
              act(() => vi.advanceTimersByTime(100));
              await act(() => new Promise(res => process.nextTick(res)));
            }

            // And now we make sure all the requests that have been sent have ended
            await waitFor(() => {
              if (requestsSent !== requestsEnded) {
                throw new Error('waiting');
              }
            });

            expect(
              unhandledRequests,
              'MSW: intercepted a request without a matching request handler. Please create a request handler for it'
            ).toEqual([]);

            await waitFor(() => {
              if (previewAnnotations.queryClient.isFetching()) {
                const pendingQueries = previewAnnotations.queryClient
                  .getQueryCache()
                  .findAll({ fetchStatus: 'fetching' });

                throw new Error(
                  'The react-query is still fetching following queries:\n' +
                    pendingQueries
                      .map((it, i) => String(i + 1) + ': ' + JSON.stringify(it.queryKey))
                      .join('\n')
                );
              }
            });

            // Cleanup listeners
            worker.events.removeListener('request:start', onStart);
            worker.events.removeListener('request:end', onEnd);
            worker.events.removeListener('request:unhandled', onUnhandledRequest);

            // Put snapshot next to the story
            const snapshotPath = path.join(
              storyDir,
              options.snapshotsDirName,
              `${componentName}.${name}${options.snapshotExtension}`
            );

            // Get rid of random id's in the ouput
            replaceUseId(document);

            document.body.removeAttribute('style');

            await expect(document.body).toMatchFileSnapshot(snapshotPath);
          },
          story.parameters?.storyshots?.timeout
        );
      });
    });
  });
});
